multiple fixes with latest CDK and cognito
stratospheric-dev/stratospheric pull request #275
Opened 2024-04-05 10:26 UTC by szantopeter

I tried to deploy chapter 10 to my AWS account, but the application wasn't working for multiple reasons

1. It deploys the stratospheric-v1 docker image, that was built from the previous chapter and has no authentication in it. There seems to be no v2 image in dockerhub, so if you agree with this approach then could you please build and publish one?
2. fix to run stack with latest CDK commandline
3. Fix misspelled property name
4. Register loadbalancer URL with cognito. I don't have a domain name so at least I could test through the loadbalancer URL

What would be additionally required
- I haven't yet read future chapters, but I assume issue 1) and 2) will be present there too. If you agree then could you publish docker images for those chapters too?
- Even after fixing all the issues and running the correct application I couldn't make login work, because cognito and the application runs on different domains, the cookies can't be shared and eventually login fails. I tried to see if the app at https://app.stratospheric.dev works, but the app isn't there. My suspicion is that it wouldn't work, because that would require cognito to be set up with a custom domain, but I don't see the CDK code doing that.

2024-04-08 16:01 UTC, szantopeter commented
@rieckpil @BjoernKW Have you had a chance to look at this PR? I made some updates and eventually the login fully works through the loadbalancer

2024-04-09 21:29 UTC, BjoernKW requested changes
In general, this pull request looks good. Thanks for the input, @szantopeter!. However, as mentioned in one comment, I'm not sure about the version increment for the Docker image.

Maybe, @rieckpil you would like to chime in, too?

2024-04-09 21:29 UTC, BjoernKW commented on chapters/chapter-10/cdk/cdk.json
I'm not sure about this change. Previously, we didn't increment that particular version number for new releases of the app and its Docker image.

2024-04-10 08:32 UTC, rieckpil commented
thank you very much for the fixes @szantopeter - In general, we don't maintain the chapter versions anymore as this is a "maintenance hell", but I'm happy to accept your changes to improve our fixes.

So LGTM, @BjoernKW feel free to integrate

2024-04-10 08:59 UTC, merged

2024-04-10 09:06 UTC, BjoernKW commented
Thanks again, @szantopeter! I've just merged your pull request (without the -v2 change for the Docker image name, though; see the comment above).

2024-04-10 12:58 UTC, szantopeter commented
Thanks for meging and even more for writing the book :) I find it much more valuable to learn through real world scenarios than to spend a lot of time on exam preparation!

Regarding the docker image name I am just unsure what was your original intentions. What happens is that

1. Developer deploys app with CDK
2. Application shows a "hello world", instead of the expected features
3. Developer realizes that the CDK config uses to the chapter 1 docker image in the public docker hub
4. Developer builds the code, pushes to his own docker hub, or ECR repo and redeploys the application
5. Application finally works

I was proposing to publish v2, v3 etc images so every chapter can be deployed independently without the need to build a docker image out of it.  

Was your plan that everyone have to build their own docker image?

2024-04-10 13:47 UTC, BjoernKW commented
> Was your plan that everyone have to build their own docker image?

Essentially, yes. This particularly applies to the chapter versions of the application, which are to be understood as intermediate steps to the final result.

2024-04-10 14:00 UTC, szantopeter commented
if that was the intention then maybe it would be better reflected by having something like this in the cdk.json

    "dockerImageUrl": "build this chapter and place your docker image URL here",

instead of 

    "dockerImageUrl": "docker.io/stratospheric/todo-app-v1:latest",

that deploys a wrong application. Though I am still not sure what is the value of everyone having to build the image for themselves, but I am fine either way. (I already build and pushed my images :) )